apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: kube-pet-node
data:
  TargetRelease: |
    Version = 0.1.2-h52.48ffc84
    BaseUrl = https://s3-us-west-2.amazonaws.com/dist.stardustapp.run/
    AutoUpgrade = true
    [Platform]
    OS = linux
    Arch = amd64
    DebUrl = deb/kube-pet-node_0.1.2-h52.48ffc84_amd64.deb
    RpmUrl = rpm/kube-pet-node-0.1.2-h52.48ffc84.x86_64.rpm
