---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-hi
  name: nginx-hi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-hi
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-hi
  name: nginx-hi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hi
  template:
    metadata:
      labels:
        app: nginx-hi
    spec:

      nodeSelector:
        purpose: pet
      tolerations:
      - key: kubernetes.io/pet-node
        operator: Exists
        effect: NoSchedule

      containers:
      - image: docker.io/nginxdemos/hello
        name: app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: X-Forwarded-Proto
              value: https
            - name: Host
              value: nginx-hi
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "600"
    kubernetes.io/ingress.class: wg69
  name: nginx-hi-int
spec:
  rules:
  - host: nginx-hi.int.wg69.net
    http:
      paths:
      - backend:
          serviceName: nginx-hi
          servicePort: 80
        path: /
