apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: nullish
    image: nullish
    ports:
    - containerPort: 80
  # nodeName: berbox
  nodeSelector:
    purpose: pet
  tolerations:
  - key: kubernetes.io/pet-node
    operator: Equal
    value: pet-berbox
    effect: NoSchedule
