---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-loop
  labels:
    app.kubernetes.io/name: slow-loop
    app.kubernetes.io/part-of: kube-pet-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: slow-loop
      app.kubernetes.io/part-of: kube-pet-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slow-loop
        app.kubernetes.io/part-of: kube-pet-node
    spec:
      automountServiceAccountToken: false
      containers:
      - name: app
        image: alpine
        command:
        - sh
        - -euxc

        - |
          while true
          do
            date
            sleep 10s
          done

      nodeSelector:
        purpose: pet
      tolerations:
      - key: kubernetes.io/pet-node
        operator: Exists
        effect: NoSchedule
